### ISSUE TITLE
why there is no 0.5* in the equation of the derivative of sate(t) 

### ISSUE THREAD

**Issue by tinymindxx** [emilianbold/swift-lstm#3]
in nicodjimenez's blog,  derivative of s(t) is get by this equation,
![image](https://user-images.githubusercontent.com/5286725/36954928-1eb2c4b4-2060-11e8-85ac-5aa3079e977d.png)
i wonder why the left of this equation is equal to the right. 
in my opinion, left = 0.5*right.
I am new to nn and lstm,  and i will appreciate if you could give some tips on this question, thanks!

**Comment by emilianbold** [comment]
I believe you are right.

Closing as the discussion moved to https://github.com/nicodjimenez/lstm/issues/33
